In [1]:
import pandas as pd

## **Extracción de muestra poblacional para el análisis posterior**

In [ ]:
## NO SE EJECUTA YA QUE NO ESTÁ ESTE DATASET EN EL REPOSITORIO POR ALTA CAPACIDAD --> 600MB
df = pd.read_csv('./data/NYC_Taxi_Cleaned_Analysis_Ready.csv')
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration_min,speed_mph,pickup_hour,day_of_week,is_weekend
0,2,2025-01-18 20:53:30,2025-01-18 21:00:47,1,0.97,1,N,238,166,1,...,1.0,13.32,0.0,0.00,0.00,7.283333,7.990847,20,Saturday,True
1,1,2025-01-25 11:12:51,2025-01-25 11:17:57,1,0.60,1,N,50,48,2,...,1.0,10.55,2.5,0.00,0.75,5.100000,7.058824,11,Saturday,True
2,1,2025-01-21 15:09:31,2025-01-21 15:19:02,1,0.80,1,N,236,237,1,...,1.0,16.65,2.5,0.00,0.00,9.516667,5.043783,15,Tuesday,False
3,2,2025-01-11 22:25:45,2025-01-11 22:34:22,2,1.93,1,N,231,68,1,...,1.0,20.37,2.5,0.00,0.75,8.616667,13.439072,22,Saturday,True
4,2,2025-01-04 23:37:07,2025-01-04 23:45:58,1,4.44,1,N,137,88,0,...,1.0,35.12,0.0,NaN,0.00,8.850000,30.101695,23,Saturday,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3946693,2,2025-11-12 22:43:32,2025-11-12 23:14:50,2,17.06,1,N,132,123,3,...,1.0,72.75,2.5,1.75,0.00,31.300000,32.702875,22,Wednesday,False
3946694,2,2025-11-03 10:04:04,2025-11-03 10:12:17,2,1.36,1,N,41,166,1,...,1.0,11.50,0.0,0.00,0.00,8.216667,9.931034,10,Monday,False
3946695,1,2025-11-17 22:52:30,2025-11-17 23:05:40,1,1.70,1,N,249,170,1,...,1.0,23.10,2.5,0.00,0.75,13.166667,7.746835,22,Monday,False
3946696,2,2025-11-02 00:34:54,2025-11-02 00:36:16,1,0.19,1,N,75,263,0,...,1.0,36.49,0.0,NaN,0.00,1.366667,8.341463,0,Sunday,True
3946697,2,2025-11-29 20:42:02,2025-11-29 21:13:00,1,2.46,1,N,234,142,1,...,1.0,31.85,2.5,0.00,0.75,30.966667,4.766416,20,Saturday,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3946698 entries, 0 to 3946697
Data columns (total 25 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   object
 2   tpep_dropoff_datetime  object
 3   passenger_count        int64
 4   trip_distance          float64
 5   RatecodeID             int64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
 20  duration_min           float64
 21  speed_mph              float64
 22  pickup_hour            int64
 23  day_of_week            object
 24  is_weekend             bool
dtypes: bool(1), float64(13), int64(7), object(4)
memory usage: 726.4+ MB

In [16]:
df_sample = df.sample(50000, random_state=42)

In [17]:
df_sample

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration_min,speed_mph,pickup_hour,day_of_week,is_weekend
2249639,2,2025-07-17 16:03:30,2025-07-17 16:35:16,1,4.71,5,N,162,112,1,...,1.0,64.03,2.5,0.00,0.75,31.766667,8.896118,16,Thursday,False
1287962,2,2025-04-10 16:05:43,2025-04-10 16:14:03,1,1.39,1,N,239,238,1,...,1.0,18.17,2.5,0.00,0.00,8.333333,10.008000,16,Thursday,False
2196316,2,2025-07-21 16:46:42,2025-07-21 16:52:43,1,0.74,1,N,113,249,1,...,1.0,16.45,2.5,0.00,0.75,6.016667,7.379501,16,Monday,False
843033,2,2025-03-07 23:20:00,2025-03-07 23:45:32,1,7.30,1,N,234,33,1,...,1.0,50.79,2.5,0.00,0.75,25.533333,17.154047,23,Friday,False
1132479,2,2025-04-05 21:54:33,2025-04-05 22:00:19,2,0.68,1,N,249,234,1,...,1.0,12.95,2.5,0.00,0.75,5.766667,7.075145,21,Saturday,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3050018,1,2025-09-09 18:14:11,2025-09-09 19:14:53,1,18.10,1,N,142,132,0,...,1.0,81.93,0.0,NaN,0.00,60.700000,17.891269,18,Tuesday,False
402922,2,2025-02-14 23:20:54,2025-02-14 23:31:24,1,1.48,1,N,113,148,1,...,1.0,20.58,2.5,0.00,0.75,10.500000,8.457143,23,Friday,False
2004471,2,2025-06-16 15:58:07,2025-06-16 16:22:05,3,3.92,1,N,68,261,1,...,1.0,35.34,2.5,0.00,0.75,23.966667,9.813630,15,Monday,False
1931871,2,2025-06-10 16:14:20,2025-06-10 16:53:16,1,8.45,1,N,138,130,2,...,1.0,50.85,0.0,1.75,0.00,38.933333,13.022260,16,Tuesday,False
526648,2,2025-02-03 16:09:26,2025-02-03 16:12:01,1,0.83,1,N,239,238,1,...,1.0,14.76,2.5,0.00,0.00,2.583333,19.277419,16,Monday,False

In [18]:
df_sample.to_csv('./data/Sample_NYC_Taxi_Analysis.csv', index=False)

In [19]:
df_1 = pd.read_csv('./data/Sample_NYC_Taxi_Analysis.csv')
df_1

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration_min,speed_mph,pickup_hour,day_of_week,is_weekend
0,2,2025-07-17 16:03:30,2025-07-17 16:35:16,1,4.71,5,N,162,112,1,...,1.0,64.03,2.5,0.00,0.75,31.766667,8.896118,16,Thursday,False
1,2,2025-04-10 16:05:43,2025-04-10 16:14:03,1,1.39,1,N,239,238,1,...,1.0,18.17,2.5,0.00,0.00,8.333333,10.008000,16,Thursday,False
2,2,2025-07-21 16:46:42,2025-07-21 16:52:43,1,0.74,1,N,113,249,1,...,1.0,16.45,2.5,0.00,0.75,6.016667,7.379501,16,Monday,False
3,2,2025-03-07 23:20:00,2025-03-07 23:45:32,1,7.30,1,N,234,33,1,...,1.0,50.79,2.5,0.00,0.75,25.533333,17.154047,23,Friday,False
4,2,2025-04-05 21:54:33,2025-04-05 22:00:19,2,0.68,1,N,249,234,1,...,1.0,12.95,2.5,0.00,0.75,5.766667,7.075145,21,Saturday,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1,2025-09-09 18:14:11,2025-09-09 19:14:53,1,18.10,1,N,142,132,0,...,1.0,81.93,0.0,NaN,0.00,60.700000,17.891269,18,Tuesday,False
49996,2,2025-02-14 23:20:54,2025-02-14 23:31:24,1,1.48,1,N,113,148,1,...,1.0,20.58,2.5,0.00,0.75,10.500000,8.457143,23,Friday,False
49997,2,2025-06-16 15:58:07,2025-06-16 16:22:05,3,3.92,1,N,68,261,1,...,1.0,35.34,2.5,0.00,0.75,23.966667,9.813630,15,Monday,False
49998,2,2025-06-10 16:14:20,2025-06-10 16:53:16,1,8.45,1,N,138,130,2,...,1.0,50.85,0.0,1.75,0.00,38.933333,13.022260,16,Tuesday,False
49999,2,2025-02-03 16:09:26,2025-02-03 16:12:01,1,0.83,1,N,239,238,1,...,1.0,14.76,2.5,0.00,0.00,2.583333,19.277419,16,Monday,False

In [20]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               50000 non-null  int64
 1   tpep_pickup_datetime   50000 non-null  object
 2   tpep_dropoff_datetime  50000 non-null  object
 3   passenger_count        50000 non-null  int64
 4   trip_distance          50000 non-null  float64
 5   RatecodeID             50000 non-null  int64
 6   store_and_fwd_flag     50000 non-null  object
 7   PULocationID           50000 non-null  int64
 8   DOLocationID           50000 non-null  int64
 9   payment_type           50000 non-null  int64
 10  fare_amount            50000 non-null  float64
 11  extra                  50000 non-null  float64
 12  mta_tax                50000 non-null  float64
 13  tip_amount             50000 non-null  float64
 14  tolls_amount           50000 non-null  float64
 15  improvement_surcharge  50000 non-null  float64
 16  total_amount           50000 non-null  float64
 17  congestion_surcharge   50000 non-null  float64
 18  Airport_fee            40331 non-null  float64
 19  cbd_congestion_fee     50000 non-null  float64
 20  duration_min           50000 non-null  float64
 21  speed_mph              50000 non-null  float64
 22  pickup_hour            50000 non-null  int64
 23  day_of_week            50000 non-null  object
 24  is_weekend             50000 non-null  bool
dtypes: bool(1), float64(13), int64(7), object(4)
memory usage: 9.2+ MB